### ISSUE TITLE
Support adding reason for preferred/deprecated rank

### ISSUE THREAD

**Issue by lucaswerkmeister** [lucaswerkmeister/tool-ranker#5]
It would be useful if [reason for preferred rank](https://www.wikidata.org/wiki/Property:P7452) or [reason for deprecation](https://www.wikidata.org/wiki/Property:P2241) qualifiers could be added when setting those ranks. Not sure how that should work in the user interface, though.

**Comment by Ainali** [comment]
In a very simple version it could be a checkbox "Add reason for rank" and when checked, it enables a field where one can add an item to set as the value for the qualifier. And depending on which button you click, the appropriate property is used.

**Comment by lucaswerkmeister** [comment]
Hm, when you put it that way, I don’t think it even needs a checkbox? There could just be an input below the buttons all the time, and it’s only used with “set to preferred/deprecated”, and with “set to normal rank” and “increment rank” it’s not used (probably with an error if it was filled in anyways). At least I assume we don’t want this for “increment rank”, even though that setting can set the rank to preferred as well.

We can even provide some nice suggestions (item ID + label) using a `<datalist>`… hm, though I guess those suggestions will mix preferred and deprecated reasons. But that should at least be relatively easy to implement (unlike a full item search component).

**Comment by lucaswerkmeister** [comment]
Hm, Test Wikidata has three “reason for deprecation” properties ([reason for deprecation:wd](https://test.wikidata.org/wiki/Property:P95780), [reason for deprecation:kdqvea](https://test.wikidata.org/wiki/Property:P94165), and [reason for deprecation:iqvwej](https://test.wikidata.org/wiki/Property:P90196), whatever those suffixes are supposed to mean), and no “reason for preferred rank” property at all as far as I can tell. We can probably just disable this feature on the test wikis.

**Comment by lucaswerkmeister** [comment]
And the suggestions in the `<datalist>` will probably just be hard-coded by hand. If we query for the most common values, the top deprecation reason by an order of magnitude is [value known, but too large for datatype](https://www.wikidata.org/wiki/Q54767019), but that’s just because somebody thought it was a good idea to import a hundred thousand primes that can’t even be represented into Wikidata, whereas I don’t think this would be a useful suggestion to human tool users.

**Comment by lucaswerkmeister** [comment]
Another thing I just realized: what should Ranker do about *existing* reasons for deprecated / preferred rank?

Probably always remove them whenever it edits a statement? (And then potentially add back a new reason if specified by the user.) The only case where an old reason should potentially be kept on an edited statement is if a reason for deprecated rank was on a statement that previously *wasn’t* deprecated rank but is now being made deprecated rank (again?), or the same for preferred rank – but that means the reason was incorrect before, so I would say it’s at best dubious whether that reason should be kept. (And it’s conceptually simpler if Ranker just *always* removes existing reasons for deprecated / preferred rank whenever it edits a statement.)

**Comment by Ainali** [comment]
> (And it’s conceptually simpler if Ranker just _always_ removes existing reasons for deprecated / preferred rank whenever it edits a statement.)

I agree that this seems simpler, and I guess that it probably also is easier to understand.

**Comment by lucaswerkmeister** [comment]
Hm, what if the statement already has the specified rank (which means it normally wouldn’t be edited at all)? Should Ranker still remove the existing reasons and then add the specified reason (if any)? I’m not so sure about that.

**Comment by lucaswerkmeister** [comment]
(It probably makes the code simpler if Ranker only updates reasons for statements where the rank is being changed, so I’m leaning towards that for now.)

**Comment by lucaswerkmeister** [comment]
This should be done now ([documentation update](https://www.wikidata.org/w/index.php?title=User:Lucas_Werkmeister/Ranker&type=revision&diff=1736418890&oldid=1581004612&diffmode=visual)).
